import Foundation

/// Master list of Thai vocabulary bundled with the app.
///
/// Pronunciations are phonetic approximations meant as a learning aid:
///  - `romanization`       uses a simplified Latin spelling (tones marked lightly).
///  - `hindiPronunciation` uses Devanagari so a Hindi speaker can sound the word out.
enum Vocabulary {
    static let all: [ThaiWord] = [
        // MARK: Greetings & everyday phrases
        ThaiWord(id: 1,  thai: "สวัสดี",       romanization: "sà-wàt-dii",        hindiPronunciation: "स-वट-दी",       englishMeaning: "hello / hi",            hindiMeaning: "नमस्ते",              category: "Greetings"),
        ThaiWord(id: 2,  thai: "ขอบคุณ",       romanization: "khòp-khun",         hindiPronunciation: "खोब-कुन",        englishMeaning: "thank you",             hindiMeaning: "धन्यवाद",             category: "Greetings"),
        ThaiWord(id: 3,  thai: "ครับ",         romanization: "kráp",              hindiPronunciation: "क्रब",           englishMeaning: "polite particle (male)", hindiMeaning: "आदरसूचक शब्द (पुरुष)", category: "Grammar"),
        ThaiWord(id: 4,  thai: "ค่ะ",          romanization: "khâ",               hindiPronunciation: "खा",             englishMeaning: "polite particle (female)", hindiMeaning: "आदरसूचक शब्द (स्त्री)", category: "Grammar"),
        ThaiWord(id: 5,  thai: "ใช่",          romanization: "châi",              hindiPronunciation: "चाइ",            englishMeaning: "yes",                   hindiMeaning: "हाँ",                 category: "Basics"),
        ThaiWord(id: 6,  thai: "ไม่",          romanization: "mâi",               hindiPronunciation: "माइ",            englishMeaning: "no / not",              hindiMeaning: "नहीं",                category: "Basics"),
        ThaiWord(id: 7,  thai: "ไม่เป็นไร",   romanization: "mâi-pen-rai",       hindiPronunciation: "माइ-पेन-राइ",   englishMeaning: "you're welcome / no problem", hindiMeaning: "कोई बात नहीं",       category: "Greetings"),
        ThaiWord(id: 8,  thai: "ขอโทษ",        romanization: "khǒo-thôot",        hindiPronunciation: "खो-थोद",         englishMeaning: "sorry / excuse me",     hindiMeaning: "माफ़ कीजिए",          category: "Greetings"),
        ThaiWord(id: 9,  thai: "สบายดีไหม",   romanization: "sà-baai-dii-mǎi",   hindiPronunciation: "स-बाइ-दी-माइ",  englishMeaning: "how are you?",          hindiMeaning: "आप कैसे हैं?",        category: "Greetings"),
        ThaiWord(id: 10, thai: "สบายดี",       romanization: "sà-baai-dii",       hindiPronunciation: "स-बाइ-दी",      englishMeaning: "I'm fine",              hindiMeaning: "मैं ठीक हूँ",         category: "Greetings"),

        // MARK: Numbers
        ThaiWord(id: 11, thai: "หนึ่ง",        romanization: "nèung",             hindiPronunciation: "नुंग",           englishMeaning: "one",                   hindiMeaning: "एक",                  category: "Numbers"),
        ThaiWord(id: 12, thai: "สอง",          romanization: "sǒong",             hindiPronunciation: "सोंग",           englishMeaning: "two",                   hindiMeaning: "दो",                  category: "Numbers"),
        ThaiWord(id: 13, thai: "สาม",          romanization: "sǎam",              hindiPronunciation: "साम",            englishMeaning: "three",                 hindiMeaning: "तीन",                 category: "Numbers"),
        ThaiWord(id: 14, thai: "สี่",          romanization: "sìi",               hindiPronunciation: "सी",             englishMeaning: "four",                  hindiMeaning: "चार",                 category: "Numbers"),
        ThaiWord(id: 15, thai: "ห้า",          romanization: "hâa",               hindiPronunciation: "हा",             englishMeaning: "five",                  hindiMeaning: "पाँच",                category: "Numbers"),
        ThaiWord(id: 16, thai: "หก",           romanization: "hòk",               hindiPronunciation: "होक",            englishMeaning: "six",                   hindiMeaning: "छह",                  category: "Numbers"),
        ThaiWord(id: 17, thai: "เจ็ด",         romanization: "jèt",               hindiPronunciation: "जेद",            englishMeaning: "seven",                 hindiMeaning: "सात",                 category: "Numbers"),
        ThaiWord(id: 18, thai: "แปด",          romanization: "pàet",              hindiPronunciation: "पैद",            englishMeaning: "eight",                 hindiMeaning: "आठ",                  category: "Numbers"),
        ThaiWord(id: 19, thai: "เก้า",         romanization: "kâo",               hindiPronunciation: "काउ",            englishMeaning: "nine",                  hindiMeaning: "नौ",                  category: "Numbers"),
        ThaiWord(id: 20, thai: "สิบ",          romanization: "sìp",               hindiPronunciation: "सिप",            englishMeaning: "ten",                   hindiMeaning: "दस",                  category: "Numbers"),

        // MARK: People
        ThaiWord(id: 21, thai: "ผม",           romanization: "phǒm",              hindiPronunciation: "पोम",            englishMeaning: "I / me (male)",         hindiMeaning: "मैं (पुरुष)",         category: "People"),
        ThaiWord(id: 22, thai: "ฉัน",          romanization: "chǎn",              hindiPronunciation: "छान",            englishMeaning: "I / me (female)",       hindiMeaning: "मैं (स्त्री)",        category: "People"),
        ThaiWord(id: 23, thai: "คุณ",          romanization: "khun",              hindiPronunciation: "कुन",            englishMeaning: "you",                   hindiMeaning: "आप / तुम",            category: "People"),
        ThaiWord(id: 24, thai: "เพื่อน",       romanization: "phûean",            hindiPronunciation: "फुअन",           englishMeaning: "friend",                hindiMeaning: "दोस्त",               category: "People"),
        ThaiWord(id: 25, thai: "ครอบครัว",    romanization: "khrôp-khrua",       hindiPronunciation: "क्रोब-क्रुआ",   englishMeaning: "family",                hindiMeaning: "परिवार",              category: "People"),

        // MARK: Food & drink
        ThaiWord(id: 26, thai: "อาหาร",        romanization: "aa-hǎan",           hindiPronunciation: "आ-हान",          englishMeaning: "food",                  hindiMeaning: "खाना / भोजन",         category: "Food"),
        ThaiWord(id: 27, thai: "น้ำ",          romanization: "náam",              hindiPronunciation: "नाम",            englishMeaning: "water",                 hindiMeaning: "पानी",                category: "Food"),
        ThaiWord(id: 28, thai: "ข้าว",         romanization: "khâao",             hindiPronunciation: "खाउ",            englishMeaning: "rice",                  hindiMeaning: "चावल",                category: "Food"),
        ThaiWord(id: 29, thai: "กิน",          romanization: "kin",               hindiPronunciation: "किन",            englishMeaning: "to eat",                hindiMeaning: "खाना (क्रिया)",       category: "Food"),
        ThaiWord(id: 30, thai: "อร่อย",        romanization: "à-ròi",             hindiPronunciation: "अ-रोइ",          englishMeaning: "delicious",             hindiMeaning: "स्वादिष्ट",           category: "Food"),
        ThaiWord(id: 31, thai: "กาแฟ",         romanization: "kaa-fae",           hindiPronunciation: "का-फै",          englishMeaning: "coffee",                hindiMeaning: "कॉफ़ी",               category: "Food"),
        ThaiWord(id: 32, thai: "ชา",           romanization: "chaa",              hindiPronunciation: "चा",             englishMeaning: "tea",                   hindiMeaning: "चाय",                 category: "Food"),
        ThaiWord(id: 33, thai: "เผ็ด",         romanization: "phèt",              hindiPronunciation: "फेद",            englishMeaning: "spicy",                 hindiMeaning: "तीखा / मसालेदार",     category: "Food"),
        ThaiWord(id: 34, thai: "หิว",          romanization: "hǐu",               hindiPronunciation: "हिउ",            englishMeaning: "hungry",                hindiMeaning: "भूखा",                category: "Food"),

        // MARK: Verbs & adjectives
        ThaiWord(id: 35, thai: "ไป",           romanization: "pai",               hindiPronunciation: "पाइ",            englishMeaning: "to go",                 hindiMeaning: "जाना",                category: "Verbs"),
        ThaiWord(id: 36, thai: "มา",           romanization: "maa",               hindiPronunciation: "मा",             englishMeaning: "to come",               hindiMeaning: "आना",                 category: "Verbs"),
        ThaiWord(id: 37, thai: "รัก",          romanization: "rák",               hindiPronunciation: "रक",             englishMeaning: "to love",               hindiMeaning: "प्यार करना",          category: "Verbs"),
        ThaiWord(id: 38, thai: "ชอบ",          romanization: "chôp",              hindiPronunciation: "चोब",            englishMeaning: "to like",               hindiMeaning: "पसंद करना",           category: "Verbs"),
        ThaiWord(id: 39, thai: "ดี",           romanization: "dii",               hindiPronunciation: "दी",             englishMeaning: "good",                  hindiMeaning: "अच्छा",               category: "Adjectives"),
        ThaiWord(id: 40, thai: "สวย",          romanization: "sǔai",              hindiPronunciation: "सुआय",           englishMeaning: "beautiful",             hindiMeaning: "सुंदर",               category: "Adjectives"),
        ThaiWord(id: 41, thai: "ใหญ่",         romanization: "yài",               hindiPronunciation: "याय",            englishMeaning: "big",                   hindiMeaning: "बड़ा",                category: "Adjectives"),
        ThaiWord(id: 42, thai: "เล็ก",         romanization: "lék",               hindiPronunciation: "लेक",            englishMeaning: "small",                 hindiMeaning: "छोटा",                category: "Adjectives"),
        ThaiWord(id: 43, thai: "ร้อน",         romanization: "rón",               hindiPronunciation: "रोन",            englishMeaning: "hot",                   hindiMeaning: "गरम",                 category: "Adjectives"),
        ThaiWord(id: 44, thai: "หนาว",         romanization: "nǎao",              hindiPronunciation: "नाउ",            englishMeaning: "cold",                  hindiMeaning: "ठंडा",                category: "Adjectives"),

        // MARK: Travel & getting around
        ThaiWord(id: 45, thai: "ห้องน้ำ",      romanization: "hông-náam",         hindiPronunciation: "होंग-नाम",       englishMeaning: "toilet / bathroom",     hindiMeaning: "शौचालय",              category: "Travel"),
        ThaiWord(id: 46, thai: "โรงแรม",       romanization: "roong-raem",        hindiPronunciation: "रोंग-रैम",       englishMeaning: "hotel",                 hindiMeaning: "होटल",                category: "Travel"),
        ThaiWord(id: 47, thai: "รถ",           romanization: "rót",               hindiPronunciation: "रोद",            englishMeaning: "car / vehicle",         hindiMeaning: "गाड़ी",               category: "Travel"),
        ThaiWord(id: 48, thai: "เท่าไหร่",     romanization: "thâo-rài",          hindiPronunciation: "ताउ-राय",        englishMeaning: "how much?",             hindiMeaning: "कितना?",              category: "Travel"),
        ThaiWord(id: 49, thai: "แพง",          romanization: "phaeng",            hindiPronunciation: "फैंग",           englishMeaning: "expensive",             hindiMeaning: "महँगा",               category: "Travel"),
        ThaiWord(id: 50, thai: "ถูก",          romanization: "thùuk",             hindiPronunciation: "थूक",            englishMeaning: "cheap",                 hindiMeaning: "सस्ता",               category: "Travel"),

        // MARK: Time
        ThaiWord(id: 51, thai: "วันนี้",       romanization: "wan-níi",           hindiPronunciation: "वन-नी",          englishMeaning: "today",                 hindiMeaning: "आज",                  category: "Time"),
        ThaiWord(id: 52, thai: "พรุ่งนี้",     romanization: "phrûng-níi",        hindiPronunciation: "फ्रुंग-नी",      englishMeaning: "tomorrow",              hindiMeaning: "कल (आने वाला)",       category: "Time"),
        ThaiWord(id: 53, thai: "เมื่อวาน",     romanization: "mûea-waan",         hindiPronunciation: "मुआ-वान",        englishMeaning: "yesterday",             hindiMeaning: "बीता कल",             category: "Time"),
        ThaiWord(id: 54, thai: "เวลา",         romanization: "wee-laa",           hindiPronunciation: "वे-ला",          englishMeaning: "time",                  hindiMeaning: "समय",                 category: "Time"),
        ThaiWord(id: 55, thai: "ชั่วโมง",      romanization: "chûa-moong",        hindiPronunciation: "चुआ-मोंग",       englishMeaning: "hour",                  hindiMeaning: "घंटा",                category: "Time"),
        ThaiWord(id: 56, thai: "นาที",         romanization: "naa-thii",          hindiPronunciation: "ना-ती",          englishMeaning: "minute",                hindiMeaning: "मिनट",                category: "Time"),
        ThaiWord(id: 57, thai: "เช้า",         romanization: "cháao",             hindiPronunciation: "चाउ",            englishMeaning: "morning",               hindiMeaning: "सुबह",                category: "Time"),
        ThaiWord(id: 58, thai: "เย็น",         romanization: "yen",               hindiPronunciation: "येन",            englishMeaning: "evening",               hindiMeaning: "शाम",                 category: "Time"),
        ThaiWord(id: 59, thai: "กลางคืน",     romanization: "klaang-khuen",      hindiPronunciation: "क्लांग-खुएन",    englishMeaning: "night",                 hindiMeaning: "रात",                 category: "Time"),
        ThaiWord(id: 60, thai: "ปี",           romanization: "pii",               hindiPronunciation: "पी",             englishMeaning: "year",                  hindiMeaning: "साल",                 category: "Time"),
        ThaiWord(id: 61, thai: "เดือน",        romanization: "duean",             hindiPronunciation: "दुअन",           englishMeaning: "month",                 hindiMeaning: "महीना",               category: "Time"),
        ThaiWord(id: 62, thai: "สัปดาห์",      romanization: "sàp-daa",           hindiPronunciation: "सप-दा",          englishMeaning: "week",                  hindiMeaning: "सप्ताह",              category: "Time"),

        // MARK: Family & people
        ThaiWord(id: 63, thai: "พ่อ",          romanization: "phôo",              hindiPronunciation: "पॉ",             englishMeaning: "father",                hindiMeaning: "पिता",                category: "Family"),
        ThaiWord(id: 64, thai: "แม่",          romanization: "mâe",               hindiPronunciation: "मै",             englishMeaning: "mother",                hindiMeaning: "माँ",                 category: "Family"),
        ThaiWord(id: 65, thai: "ลูก",          romanization: "lûuk",              hindiPronunciation: "लूक",            englishMeaning: "child (son/daughter)",  hindiMeaning: "संतान / बच्चा",       category: "Family"),
        ThaiWord(id: 66, thai: "พี่",          romanization: "phîi",              hindiPronunciation: "पी",             englishMeaning: "older sibling",         hindiMeaning: "बड़ा भाई / बड़ी बहन", category: "Family"),
        ThaiWord(id: 67, thai: "น้อง",         romanization: "nóong",             hindiPronunciation: "नोंग",           englishMeaning: "younger sibling",       hindiMeaning: "छोटा भाई / छोटी बहन", category: "Family"),
        ThaiWord(id: 68, thai: "ผู้ชาย",       romanization: "phûu-chaai",        hindiPronunciation: "पू-चाय",         englishMeaning: "man",                   hindiMeaning: "आदमी",                category: "People"),
        ThaiWord(id: 69, thai: "ผู้หญิง",      romanization: "phûu-yǐng",         hindiPronunciation: "पू-यिंग",        englishMeaning: "woman",                 hindiMeaning: "औरत",                 category: "People"),
        ThaiWord(id: 70, thai: "เด็ก",         romanization: "dèk",               hindiPronunciation: "देक",            englishMeaning: "child / kid",           hindiMeaning: "बच्चा",               category: "People"),
        ThaiWord(id: 71, thai: "ชื่อ",         romanization: "chûue",             hindiPronunciation: "चू",             englishMeaning: "name",                  hindiMeaning: "नाम",                 category: "People"),
        ThaiWord(id: 72, thai: "ครู",          romanization: "khruu",             hindiPronunciation: "क्रू",           englishMeaning: "teacher",               hindiMeaning: "शिक्षक",              category: "People"),

        // MARK: Body & health
        ThaiWord(id: 73, thai: "หัว",          romanization: "hǔa",               hindiPronunciation: "हुआ",            englishMeaning: "head",                  hindiMeaning: "सिर",                 category: "Body"),
        ThaiWord(id: 74, thai: "ตา",           romanization: "taa",               hindiPronunciation: "ता",             englishMeaning: "eye",                   hindiMeaning: "आँख",                 category: "Body"),
        ThaiWord(id: 75, thai: "มือ",          romanization: "muue",              hindiPronunciation: "मू",             englishMeaning: "hand",                  hindiMeaning: "हाथ",                 category: "Body"),
        ThaiWord(id: 76, thai: "ใจ",           romanization: "jai",               hindiPronunciation: "जाय",            englishMeaning: "heart / mind",          hindiMeaning: "दिल / मन",            category: "Body"),
        ThaiWord(id: 77, thai: "ฟัน",          romanization: "fan",               hindiPronunciation: "फन",             englishMeaning: "tooth",                 hindiMeaning: "दाँत",                category: "Body"),
        ThaiWord(id: 78, thai: "ปวด",          romanization: "pùat",              hindiPronunciation: "पुआद",           englishMeaning: "to ache / pain",        hindiMeaning: "दर्द होना",           category: "Health"),
        ThaiWord(id: 79, thai: "ป่วย",         romanization: "pùai",              hindiPronunciation: "पुआय",           englishMeaning: "sick / ill",            hindiMeaning: "बीमार",               category: "Health"),
        ThaiWord(id: 80, thai: "หมอ",          romanization: "mǒo",               hindiPronunciation: "मो",             englishMeaning: "doctor",                hindiMeaning: "डॉक्टर",              category: "Health"),
        ThaiWord(id: 81, thai: "ยา",           romanization: "yaa",               hindiPronunciation: "या",             englishMeaning: "medicine",              hindiMeaning: "दवा",                 category: "Health"),
        ThaiWord(id: 82, thai: "โรงพยาบาล",   romanization: "roong-phá-yaa-baan", hindiPronunciation: "रोंग-पया-बान",  englishMeaning: "hospital",              hindiMeaning: "अस्पताल",             category: "Health"),

        // MARK: Colors
        ThaiWord(id: 83, thai: "สี",           romanization: "sǐi",               hindiPronunciation: "सी",             englishMeaning: "color",                 hindiMeaning: "रंग",                 category: "Colors"),
        ThaiWord(id: 84, thai: "แดง",          romanization: "daeng",             hindiPronunciation: "दैंग",           englishMeaning: "red",                   hindiMeaning: "लाल",                 category: "Colors"),
        ThaiWord(id: 85, thai: "ขาว",          romanization: "khǎao",             hindiPronunciation: "खाउ",            englishMeaning: "white",                 hindiMeaning: "सफ़ेद",               category: "Colors"),
        ThaiWord(id: 86, thai: "ดำ",           romanization: "dam",               hindiPronunciation: "दम",             englishMeaning: "black",                 hindiMeaning: "काला",                category: "Colors"),
        ThaiWord(id: 87, thai: "เขียว",        romanization: "khǐao",             hindiPronunciation: "खियाउ",          englishMeaning: "green",                 hindiMeaning: "हरा",                 category: "Colors"),
        ThaiWord(id: 88, thai: "ฟ้า",          romanization: "fáa",               hindiPronunciation: "फ़ा",            englishMeaning: "blue (sky blue)",       hindiMeaning: "नीला / आसमानी",       category: "Colors"),
        ThaiWord(id: 89, thai: "เหลือง",       romanization: "lǔeang",            hindiPronunciation: "लुअंग",          englishMeaning: "yellow",                hindiMeaning: "पीला",                category: "Colors"),

        // MARK: Nature & weather
        ThaiWord(id: 90, thai: "ฝน",           romanization: "fǒn",               hindiPronunciation: "फ़ोन",           englishMeaning: "rain",                  hindiMeaning: "बारिश",               category: "Nature"),
        ThaiWord(id: 91, thai: "แดด",          romanization: "dàet",              hindiPronunciation: "दैद",            englishMeaning: "sunshine",              hindiMeaning: "धूप",                 category: "Nature"),
        ThaiWord(id: 92, thai: "ลม",           romanization: "lom",               hindiPronunciation: "लोम",            englishMeaning: "wind",                  hindiMeaning: "हवा",                 category: "Nature"),
        ThaiWord(id: 93, thai: "ทะเล",         romanization: "thá-lee",           hindiPronunciation: "त-ले",           englishMeaning: "sea",                   hindiMeaning: "समुद्र",              category: "Nature"),
        ThaiWord(id: 94, thai: "ภูเขา",        romanization: "phuu-khǎo",         hindiPronunciation: "पू-खाउ",         englishMeaning: "mountain",              hindiMeaning: "पहाड़",               category: "Nature"),
        ThaiWord(id: 95, thai: "ต้นไม้",       romanization: "tôn-mái",           hindiPronunciation: "तोन-माय",        englishMeaning: "tree",                  hindiMeaning: "पेड़",                category: "Nature"),
        ThaiWord(id: 96, thai: "ดอกไม้",       romanization: "dòk-mái",           hindiPronunciation: "दोक-माय",        englishMeaning: "flower",                hindiMeaning: "फूल",                 category: "Nature"),
        ThaiWord(id: 97, thai: "อากาศ",        romanization: "aa-kàat",           hindiPronunciation: "आ-काद",          englishMeaning: "weather / air",         hindiMeaning: "मौसम / हवा",          category: "Nature"),

        // MARK: Places
        ThaiWord(id: 98,  thai: "บ้าน",        romanization: "bâan",              hindiPronunciation: "बान",            englishMeaning: "house / home",          hindiMeaning: "घर",                  category: "Places"),
        ThaiWord(id: 99,  thai: "ตลาด",        romanization: "tà-làat",           hindiPronunciation: "त-लाद",          englishMeaning: "market",                hindiMeaning: "बाज़ार",              category: "Places"),
        ThaiWord(id: 100, thai: "ร้าน",        romanization: "ráan",              hindiPronunciation: "रान",            englishMeaning: "shop",                  hindiMeaning: "दुकान",               category: "Places"),
        ThaiWord(id: 101, thai: "ร้านอาหาร",   romanization: "ráan-aa-hǎan",      hindiPronunciation: "रान-आ-हान",     englishMeaning: "restaurant",            hindiMeaning: "रेस्टोरेंट",          category: "Places"),
        ThaiWord(id: 102, thai: "โรงเรียน",    romanization: "roong-rian",        hindiPronunciation: "रोंग-रियन",      englishMeaning: "school",                hindiMeaning: "स्कूल",               category: "Places"),
        ThaiWord(id: 103, thai: "วัด",         romanization: "wát",               hindiPronunciation: "वद",             englishMeaning: "temple",                hindiMeaning: "मंदिर",               category: "Places"),
        ThaiWord(id: 104, thai: "สนามบิน",     romanization: "sà-nǎam-bin",       hindiPronunciation: "स-नाम-बिन",     englishMeaning: "airport",               hindiMeaning: "हवाई अड्डा",          category: "Places"),
        ThaiWord(id: 105, thai: "ธนาคาร",      romanization: "thá-naa-khaan",     hindiPronunciation: "त-ना-खान",      englishMeaning: "bank",                  hindiMeaning: "बैंक",                category: "Places"),
        ThaiWord(id: 106, thai: "ถนน",         romanization: "thà-nǒn",           hindiPronunciation: "थ-नोन",          englishMeaning: "road / street",         hindiMeaning: "सड़क",                category: "Places"),
        ThaiWord(id: 107, thai: "เมือง",       romanization: "mueang",            hindiPronunciation: "मुअंग",          englishMeaning: "city / town",           hindiMeaning: "शहर",                 category: "Places"),
        ThaiWord(id: 108, thai: "ประเทศ",      romanization: "prà-thêet",         hindiPronunciation: "प्र-तेद",        englishMeaning: "country",               hindiMeaning: "देश",                 category: "Places"),

        // MARK: Money & shopping
        ThaiWord(id: 109, thai: "เงิน",        romanization: "ngoen",             hindiPronunciation: "ङर्न",             englishMeaning: "money",                 hindiMeaning: "पैसा",                category: "Money"),
        ThaiWord(id: 110, thai: "บาท",         romanization: "bàat",              hindiPronunciation: "बाद",            englishMeaning: "baht (Thai currency)",  hindiMeaning: "बात (थाई मुद्रा)",    category: "Money"),
        ThaiWord(id: 111, thai: "ซื้อ",        romanization: "súue",              hindiPronunciation: "सू",             englishMeaning: "to buy",                hindiMeaning: "खरीदना",              category: "Money"),
        ThaiWord(id: 112, thai: "ขาย",         romanization: "khǎai",             hindiPronunciation: "खाय",            englishMeaning: "to sell",               hindiMeaning: "बेचना",               category: "Money"),
        ThaiWord(id: 113, thai: "ลดราคา",      romanization: "lót-raa-khaa",      hindiPronunciation: "लोद-रा-खा",     englishMeaning: "discount",              hindiMeaning: "छूट",                 category: "Money"),
        ThaiWord(id: 114, thai: "ฟรี",         romanization: "frii",              hindiPronunciation: "फ्री",           englishMeaning: "free (no cost)",        hindiMeaning: "मुफ़्त",              category: "Money"),

        // MARK: More verbs
        ThaiWord(id: 115, thai: "พูด",         romanization: "phûut",             hindiPronunciation: "फूद",            englishMeaning: "to speak",              hindiMeaning: "बोलना",               category: "Verbs"),
        ThaiWord(id: 116, thai: "ฟัง",         romanization: "fang",              hindiPronunciation: "फंग",            englishMeaning: "to listen",             hindiMeaning: "सुनना",               category: "Verbs"),
        ThaiWord(id: 117, thai: "อ่าน",        romanization: "àan",               hindiPronunciation: "आन",             englishMeaning: "to read",               hindiMeaning: "पढ़ना",               category: "Verbs"),
        ThaiWord(id: 118, thai: "เขียน",       romanization: "khǐan",             hindiPronunciation: "खियन",           englishMeaning: "to write",              hindiMeaning: "लिखना",               category: "Verbs"),
        ThaiWord(id: 119, thai: "ดู",          romanization: "duu",               hindiPronunciation: "दू",             englishMeaning: "to look / watch",       hindiMeaning: "देखना",               category: "Verbs"),
        ThaiWord(id: 120, thai: "นอน",         romanization: "noon",              hindiPronunciation: "नोन",            englishMeaning: "to sleep",              hindiMeaning: "सोना",                category: "Verbs"),
        ThaiWord(id: 121, thai: "ตื่น",        romanization: "tùuen",             hindiPronunciation: "तून",            englishMeaning: "to wake up",            hindiMeaning: "जागना",               category: "Verbs"),
        ThaiWord(id: 122, thai: "ทำ",          romanization: "tham",              hindiPronunciation: "तम",             englishMeaning: "to do / make",          hindiMeaning: "करना",                category: "Verbs"),
        ThaiWord(id: 123, thai: "ทำงาน",       romanization: "tham-ngaan",        hindiPronunciation: "तम-ङान",        englishMeaning: "to work",               hindiMeaning: "काम करना",            category: "Verbs"),
        ThaiWord(id: 124, thai: "เดิน",        romanization: "doen",              hindiPronunciation: "दर्न",             englishMeaning: "to walk",               hindiMeaning: "चलना / टहलना",        category: "Verbs"),
        ThaiWord(id: 125, thai: "วิ่ง",        romanization: "wîng",              hindiPronunciation: "विंग",           englishMeaning: "to run",                hindiMeaning: "दौड़ना",              category: "Verbs"),
        ThaiWord(id: 126, thai: "เข้าใจ",      romanization: "khâo-jai",          hindiPronunciation: "खाउ-जाय",       englishMeaning: "to understand",         hindiMeaning: "समझना",               category: "Verbs"),
        ThaiWord(id: 127, thai: "รู้",          romanization: "rúu",               hindiPronunciation: "रू",             englishMeaning: "to know",               hindiMeaning: "जानना",               category: "Verbs"),
        ThaiWord(id: 128, thai: "คิด",         romanization: "khít",              hindiPronunciation: "खित",            englishMeaning: "to think",              hindiMeaning: "सोचना",               category: "Verbs"),
        ThaiWord(id: 129, thai: "ช่วย",        romanization: "chûai",             hindiPronunciation: "चुआय",           englishMeaning: "to help",               hindiMeaning: "मदद करना",            category: "Verbs"),
        ThaiWord(id: 130, thai: "รอ",          romanization: "roo",               hindiPronunciation: "रो",             englishMeaning: "to wait",               hindiMeaning: "इंतज़ार करना",        category: "Verbs"),
        ThaiWord(id: 131, thai: "หยุด",        romanization: "yùt",               hindiPronunciation: "युद",            englishMeaning: "to stop",               hindiMeaning: "रुकना",               category: "Verbs"),
        ThaiWord(id: 132, thai: "เปิด",        romanization: "pòet",              hindiPronunciation: "पर्द",             englishMeaning: "to open / turn on",     hindiMeaning: "खोलना / चालू करना",   category: "Verbs"),
        ThaiWord(id: 133, thai: "ปิด",         romanization: "pìt",               hindiPronunciation: "पिद",            englishMeaning: "to close / turn off",   hindiMeaning: "बंद करना",            category: "Verbs"),

        // MARK: More adjectives
        ThaiWord(id: 134, thai: "ใหม่",        romanization: "mài",               hindiPronunciation: "माय",            englishMeaning: "new",                   hindiMeaning: "नया",                 category: "Adjectives"),
        ThaiWord(id: 135, thai: "เก่า",        romanization: "kào",               hindiPronunciation: "काव",            englishMeaning: "old (things)",          hindiMeaning: "पुराना",              category: "Adjectives"),
        ThaiWord(id: 136, thai: "เร็ว",        romanization: "reo",               hindiPronunciation: "रेव",            englishMeaning: "fast",                  hindiMeaning: "तेज़",                category: "Adjectives"),
        ThaiWord(id: 137, thai: "ช้า",         romanization: "cháa",              hindiPronunciation: "चा",             englishMeaning: "slow",                  hindiMeaning: "धीमा",                category: "Adjectives"),
        ThaiWord(id: 138, thai: "ง่าย",        romanization: "ngâai",             hindiPronunciation: "ङाय",            englishMeaning: "easy",                  hindiMeaning: "आसान",                category: "Adjectives"),
        ThaiWord(id: 139, thai: "ยาก",         romanization: "yâak",              hindiPronunciation: "याक",            englishMeaning: "difficult",             hindiMeaning: "कठिन / मुश्किल",      category: "Adjectives"),
        ThaiWord(id: 140, thai: "สนุก",        romanization: "sà-nùk",            hindiPronunciation: "स-नुक",          englishMeaning: "fun / enjoyable",       hindiMeaning: "मज़ेदार",             category: "Adjectives"),
        ThaiWord(id: 141, thai: "เหนื่อย",     romanization: "nùeai",             hindiPronunciation: "नुअय",           englishMeaning: "tired",                 hindiMeaning: "थका हुआ",             category: "Adjectives"),
        ThaiWord(id: 142, thai: "หวาน",        romanization: "wǎan",              hindiPronunciation: "वान",            englishMeaning: "sweet",                 hindiMeaning: "मीठा",                category: "Adjectives"),
        ThaiWord(id: 143, thai: "ใกล้",        romanization: "klâi",              hindiPronunciation: "क्लाय",          englishMeaning: "near",                  hindiMeaning: "पास / नज़दीक",        category: "Adjectives"),
        ThaiWord(id: 144, thai: "ไกล",         romanization: "klai",              hindiPronunciation: "क्लाय",          englishMeaning: "far",                   hindiMeaning: "दूर",                 category: "Adjectives"),

        // MARK: Question words & connectors
        ThaiWord(id: 145, thai: "อะไร",        romanization: "à-rai",             hindiPronunciation: "अ-राय",          englishMeaning: "what?",                 hindiMeaning: "क्या?",               category: "Questions"),
        ThaiWord(id: 146, thai: "ที่ไหน",      romanization: "thîi-nǎi",          hindiPronunciation: "ती-नाय",         englishMeaning: "where?",                hindiMeaning: "कहाँ?",               category: "Questions"),
        ThaiWord(id: 147, thai: "เมื่อไหร่",   romanization: "mûea-rài",          hindiPronunciation: "मुआ-राय",        englishMeaning: "when?",                 hindiMeaning: "कब?",                 category: "Questions"),
        ThaiWord(id: 148, thai: "ทำไม",        romanization: "tham-mai",          hindiPronunciation: "तम-माय",         englishMeaning: "why?",                  hindiMeaning: "क्यों?",              category: "Questions"),
        ThaiWord(id: 149, thai: "ใคร",         romanization: "khrai",             hindiPronunciation: "ख्राय",          englishMeaning: "who?",                  hindiMeaning: "कौन?",                category: "Questions"),
        ThaiWord(id: 150, thai: "ยังไง",       romanization: "yang-ngai",         hindiPronunciation: "यंग-ङाय",        englishMeaning: "how?",                  hindiMeaning: "कैसे?",               category: "Questions"),
        ThaiWord(id: 151, thai: "และ",         romanization: "láe",               hindiPronunciation: "लै",             englishMeaning: "and",                   hindiMeaning: "और",                  category: "Grammar"),
        ThaiWord(id: 152, thai: "หรือ",        romanization: "rǔue",              hindiPronunciation: "रू",             englishMeaning: "or",                    hindiMeaning: "या",                  category: "Grammar"),
        ThaiWord(id: 153, thai: "แต่",         romanization: "tàe",               hindiPronunciation: "तै",             englishMeaning: "but",                   hindiMeaning: "लेकिन",               category: "Grammar"),
        ThaiWord(id: 154, thai: "นี่",         romanization: "nîi",               hindiPronunciation: "नी",             englishMeaning: "this",                  hindiMeaning: "यह",                  category: "Grammar"),
        ThaiWord(id: 155, thai: "นั่น",        romanization: "nân",               hindiPronunciation: "नन",             englishMeaning: "that",                  hindiMeaning: "वह",                  category: "Grammar"),

        // MARK: Animals
        ThaiWord(id: 156, thai: "หมา",         romanization: "mǎa",               hindiPronunciation: "मा",             englishMeaning: "dog",                   hindiMeaning: "कुत्ता",              category: "Animals"),
        ThaiWord(id: 157, thai: "แมว",         romanization: "maeo",              hindiPronunciation: "मैव",            englishMeaning: "cat",                   hindiMeaning: "बिल्ली",              category: "Animals"),
        ThaiWord(id: 158, thai: "นก",          romanization: "nók",               hindiPronunciation: "नोक",            englishMeaning: "bird",                  hindiMeaning: "चिड़िया",             category: "Animals"),
        ThaiWord(id: 159, thai: "ปลา",         romanization: "plaa",              hindiPronunciation: "प्ला",           englishMeaning: "fish",                  hindiMeaning: "मछली",                category: "Animals"),
        ThaiWord(id: 160, thai: "ช้าง",        romanization: "cháang",            hindiPronunciation: "चांग",           englishMeaning: "elephant",              hindiMeaning: "हाथी",                category: "Animals"),

        // MARK: More food
        ThaiWord(id: 161, thai: "ผลไม้",       romanization: "phǒn-lá-mái",       hindiPronunciation: "फ़ोन-ल-माय",    englishMeaning: "fruit",                 hindiMeaning: "फल",                  category: "Food"),
        ThaiWord(id: 162, thai: "ผัก",         romanization: "phàk",              hindiPronunciation: "फक",             englishMeaning: "vegetable",             hindiMeaning: "सब्ज़ी",              category: "Food"),
        ThaiWord(id: 163, thai: "ไก่",         romanization: "kài",               hindiPronunciation: "काय",            englishMeaning: "chicken",               hindiMeaning: "मुर्गी / चिकन",       category: "Food"),
        ThaiWord(id: 164, thai: "ไข่",         romanization: "khài",              hindiPronunciation: "खाय",            englishMeaning: "egg",                   hindiMeaning: "अंडा",                category: "Food"),
        ThaiWord(id: 165, thai: "นม",          romanization: "num",               hindiPronunciation: "नम",             englishMeaning: "milk",                  hindiMeaning: "दूध",                 category: "Food"),
        ThaiWord(id: 166, thai: "น้ำตาล",      romanization: "nám-taan",          hindiPronunciation: "नम-तान",        englishMeaning: "sugar",                 hindiMeaning: "चीनी",                category: "Food"),
        ThaiWord(id: 167, thai: "เกลือ",       romanization: "kluea",             hindiPronunciation: "क्लुआ",          englishMeaning: "salt",                  hindiMeaning: "नमक",                 category: "Food"),
        ThaiWord(id: 168, thai: "แกง",         romanization: "kaeng",             hindiPronunciation: "कैंग",           englishMeaning: "curry",                 hindiMeaning: "करी",                 category: "Food"),
        ThaiWord(id: 169, thai: "ก๋วยเตี๋ยว",  romanization: "kǔai-tǐao",         hindiPronunciation: "कुआय-तियाव",    englishMeaning: "noodles",               hindiMeaning: "नूडल्स",              category: "Food"),

        // MARK: Safety & essentials
        ThaiWord(id: 170, thai: "ช่วยด้วย",    romanization: "chûai-dûai",        hindiPronunciation: "चुआय-दुआय",     englishMeaning: "help! (emergency)",     hindiMeaning: "बचाओ! / मदद करो!",    category: "Safety"),
        ThaiWord(id: 171, thai: "ตำรวจ",       romanization: "tam-rùat",          hindiPronunciation: "तम-रुआद",        englishMeaning: "police",                hindiMeaning: "पुलिस",               category: "Safety"),
        ThaiWord(id: 172, thai: "อันตราย",     romanization: "an-tà-raai",        hindiPronunciation: "अन-त-राय",       englishMeaning: "danger / dangerous",    hindiMeaning: "खतरा / खतरनाक",       category: "Safety"),
        ThaiWord(id: 173, thai: "ระวัง",       romanization: "rá-wang",           hindiPronunciation: "र-वंग",          englishMeaning: "careful! / watch out",  hindiMeaning: "सावधान!",             category: "Safety"),
        ThaiWord(id: 174, thai: "โทรศัพท์",    romanization: "thoo-rá-sàp",       hindiPronunciation: "तो-र-सप",        englishMeaning: "telephone",             hindiMeaning: "फ़ोन",                category: "Safety"),

        // MARK: Directions
        ThaiWord(id: 175, thai: "ซ้าย",        romanization: "sáai",              hindiPronunciation: "साय",            englishMeaning: "left (side)",           hindiMeaning: "बायाँ",               category: "Directions"),
        ThaiWord(id: 176, thai: "ขวา",         romanization: "khwǎa",             hindiPronunciation: "ख्वा",           englishMeaning: "right (side)",          hindiMeaning: "दायाँ",               category: "Directions"),
        ThaiWord(id: 177, thai: "ตรงไป",       romanization: "trong-pai",         hindiPronunciation: "त्रोंग-पाय",     englishMeaning: "straight ahead",        hindiMeaning: "सीधे",                category: "Directions"),
        ThaiWord(id: 178, thai: "ที่นี่",      romanization: "thîi-nîi",          hindiPronunciation: "ती-नी",          englishMeaning: "here",                  hindiMeaning: "यहाँ",                category: "Directions"),
        ThaiWord(id: 179, thai: "ที่นั่น",     romanization: "thîi-nân",          hindiPronunciation: "ती-नन",          englishMeaning: "there",                 hindiMeaning: "वहाँ",                category: "Directions"),
        ThaiWord(id: 180, thai: "ข้างบน",      romanization: "khâang-bon",        hindiPronunciation: "खांग-बोन",       englishMeaning: "above / upstairs",      hindiMeaning: "ऊपर",                 category: "Directions"),
        ThaiWord(id: 181, thai: "ข้างล่าง",    romanization: "khâang-lâang",      hindiPronunciation: "खांग-लांग",      englishMeaning: "below / downstairs",    hindiMeaning: "नीचे",                category: "Directions"),

        // MARK: Compounds of earlier words (power the "related words" chips)
        ThaiWord(id: 182, thai: "น้ำแข็ง",     romanization: "nám-khǎeng",        hindiPronunciation: "नम-खैंग",       englishMeaning: "ice",                   hindiMeaning: "बर्फ़",               category: "Food"),
        ThaiWord(id: 183, thai: "ข้าวผัด",     romanization: "khâao-phàt",        hindiPronunciation: "खाउ-फद",         englishMeaning: "fried rice",            hindiMeaning: "फ्राइड राइस",         category: "Food"),
        ThaiWord(id: 184, thai: "น้ำส้ม",      romanization: "nám-sôm",           hindiPronunciation: "नम-सोम",        englishMeaning: "orange juice",          hindiMeaning: "संतरे का रस",         category: "Food"),
        ThaiWord(id: 185, thai: "ไฟ",          romanization: "fai",               hindiPronunciation: "फाय",            englishMeaning: "fire / light",          hindiMeaning: "आग / बत्ती",          category: "Basics"),
        ThaiWord(id: 186, thai: "รถไฟ",        romanization: "rót-fai",           hindiPronunciation: "रोद-फाय",        englishMeaning: "train",                 hindiMeaning: "रेलगाड़ी",            category: "Travel"),

        // MARK: Feelings, shopping & travel extras (agent batch 2)
        ThaiWord(id: 187, thai: "ดีใจ", romanization: "dii-jai", hindiPronunciation: "दी-जय", englishMeaning: "happy / glad", hindiMeaning: "खुश", category: "Feelings"),
        ThaiWord(id: 188, thai: "เสียใจ", romanization: "sǐa-jai", hindiPronunciation: "सिया-जय", englishMeaning: "sad", hindiMeaning: "दुखी", category: "Feelings"),
        ThaiWord(id: 189, thai: "โกรธ", romanization: "kròot", hindiPronunciation: "ग्रोत", englishMeaning: "angry", hindiMeaning: "गुस्सा / नाराज़", category: "Feelings"),
        ThaiWord(id: 190, thai: "เบื่อ", romanization: "bùea", hindiPronunciation: "बुआ", englishMeaning: "bored", hindiMeaning: "बोर / ऊबा हुआ", category: "Feelings"),
        ThaiWord(id: 191, thai: "ตื่นเต้น", romanization: "tùun-tên", hindiPronunciation: "तून-तेन", englishMeaning: "excited", hindiMeaning: "उत्साहित", category: "Feelings"),
        ThaiWord(id: 192, thai: "คิดถึง", romanization: "kít-tǔng", hindiPronunciation: "खित-थुंग", englishMeaning: "to miss (someone)", hindiMeaning: "याद आना", category: "Feelings"),
        ThaiWord(id: 193, thai: "เจอ", romanization: "jer", hindiPronunciation: "जर्", englishMeaning: "to meet / run into", hindiMeaning: "मिलना", category: "Basics"),
        ThaiWord(id: 194, thai: "รอสักครู่", romanization: "ror-sàk-krûu", hindiPronunciation: "रॉ-सक-ख्रू", englishMeaning: "wait a moment", hindiMeaning: "ज़रा रुकिए", category: "Basics"),
        ThaiWord(id: 195, thai: "อาจจะ", romanization: "àat-jà", hindiPronunciation: "आत-ज", englishMeaning: "maybe / perhaps", hindiMeaning: "शायद", category: "Basics"),
        ThaiWord(id: 196, thai: "แน่นอน", romanization: "nâe-non", hindiPronunciation: "नै-नॉन", englishMeaning: "sure / certainly", hindiMeaning: "ज़रूर / पक्का", category: "Basics"),
        ThaiWord(id: 197, thai: "ด้วยกัน", romanization: "dûai-kan", hindiPronunciation: "दुआय-गन", englishMeaning: "together", hindiMeaning: "साथ में / एक साथ", category: "Basics"),
        ThaiWord(id: 198, thai: "คนเดียว", romanization: "kon-diao", hindiPronunciation: "खोन-दियाव", englishMeaning: "alone", hindiMeaning: "अकेला", category: "Basics"),
        ThaiWord(id: 199, thai: "กระเป๋า", romanization: "krà-pǎo", hindiPronunciation: "ग्र-पाओ", englishMeaning: "bag", hindiMeaning: "बैग / थैला", category: "Shopping"),
        ThaiWord(id: 200, thai: "เสื้อ", romanization: "sûea", hindiPronunciation: "सूआ", englishMeaning: "shirt", hindiMeaning: "शर्ट / कमीज़", category: "Shopping"),
        ThaiWord(id: 201, thai: "รองเท้า", romanization: "rawng-táao", hindiPronunciation: "रॉंग-थाओ", englishMeaning: "shoes", hindiMeaning: "जूते", category: "Shopping"),
        ThaiWord(id: 202, thai: "ที่ชาร์จ", romanization: "tîi-châat", hindiPronunciation: "थी-छात", englishMeaning: "charger (phone)", hindiMeaning: "चार्जर", category: "Shopping"),
        ThaiWord(id: 203, thai: "ต่อราคา", romanization: "tàw-raa-khaa", hindiPronunciation: "तॉ-रा-खा", englishMeaning: "to bargain / haggle", hindiMeaning: "मोल-भाव करना", category: "Shopping"),
        ThaiWord(id: 204, thai: "ลดหน่อยได้ไหม", romanization: "lót-nòi-dâi-mǎi", hindiPronunciation: "लोत-नॉय-दाय-माय", englishMeaning: "can you lower the price a bit?", hindiMeaning: "थोड़ा कम कर सकते हैं?", category: "Shopping"),
        ThaiWord(id: 205, thai: "ไซส์", romanization: "sái", hindiPronunciation: "साय", englishMeaning: "size", hindiMeaning: "साइज़ / नाप", category: "Shopping"),
        ThaiWord(id: 206, thai: "พอดี", romanization: "phaw-dii", hindiPronunciation: "फॉ-दी", englishMeaning: "just right / fits well", hindiMeaning: "बिलकुल ठीक / फिट", category: "Shopping"),
        ThaiWord(id: 207, thai: "ลอง", romanization: "lawng", hindiPronunciation: "लॉंग", englishMeaning: "to try / try on", hindiMeaning: "आज़माना / पहनकर देखना", category: "Shopping"),
        ThaiWord(id: 208, thai: "ใบเสร็จ", romanization: "bai-sèt", hindiPronunciation: "बाय-सेत", englishMeaning: "receipt", hindiMeaning: "रसीद", category: "Shopping"),
        ThaiWord(id: 209, thai: "ถุงพลาสติก", romanization: "tǔng-pláat-sà-tìk", hindiPronunciation: "थुंग-फ्लात-स-तिक", englishMeaning: "plastic bag", hindiMeaning: "प्लास्टिक की थैली", category: "Shopping"),
        ThaiWord(id: 210, thai: "กี่โมง", romanization: "kìi-mohng", hindiPronunciation: "गी-मोंग", englishMeaning: "what time?", hindiMeaning: "कितने बजे?", category: "Shopping"),
        ThaiWord(id: 211, thai: "ชายหาด", romanization: "chaai-hàat", hindiPronunciation: "चाय-हात", englishMeaning: "beach", hindiMeaning: "समुद्र तट / बीच", category: "Travel"),
        ThaiWord(id: 212, thai: "เกาะ", romanization: "kò", hindiPronunciation: "गॉ", englishMeaning: "island", hindiMeaning: "द्वीप / टापू", category: "Travel"),
        ThaiWord(id: 213, thai: "ตั๋ว", romanization: "tǔa", hindiPronunciation: "तुआ", englishMeaning: "ticket", hindiMeaning: "टिकट", category: "Travel"),
        ThaiWord(id: 214, thai: "เรือ", romanization: "rʉa", hindiPronunciation: "रुआ", englishMeaning: "boat", hindiMeaning: "नाव", category: "Travel"),
        ThaiWord(id: 215, thai: "วินมอเตอร์ไซค์", romanization: "win-moo-ter-sai", hindiPronunciation: "विन-मॉ-टर्-साय", englishMeaning: "motorbike taxi", hindiMeaning: "बाइक टैक्सी", category: "Travel"),
        ThaiWord(id: 216, thai: "ข้าวเหนียวมะม่วง", romanization: "khâao-nǐao má-mûang", hindiPronunciation: "खाओ-नियाव-म-मुआंग", englishMeaning: "mango sticky rice", hindiMeaning: "मैंगो स्टिकी राइस", category: "Food"),
        ThaiWord(id: 217, thai: "ส้มตำ", romanization: "sôm-tam", hindiPronunciation: "सोम-तम", englishMeaning: "som tam (papaya salad)", hindiMeaning: "सोम-तम (कच्चे पपीते का तीखा सलाद)", category: "Food"),
        ThaiWord(id: 218, thai: "ผัดไทย", romanization: "phàt-thai", hindiPronunciation: "फत-थाई", englishMeaning: "pad thai", hindiMeaning: "पैड थाई (थाई भुनी नूडल्स)", category: "Food"),
        ThaiWord(id: 219, thai: "ขวดน้ำ", romanization: "khùat náam", hindiPronunciation: "खुआत-नाम", englishMeaning: "water bottle", hindiMeaning: "पानी की बोतल", category: "Food"),
        ThaiWord(id: 220, thai: "เช็คบิล", romanization: "chék-bin", hindiPronunciation: "चेक-बिन", englishMeaning: "bill / check (restaurant)", hindiMeaning: "बिल", category: "Food"),
        ThaiWord(id: 221, thai: "ช้อน", romanization: "chóon", hindiPronunciation: "चॉन", englishMeaning: "spoon", hindiMeaning: "चम्मच", category: "Food"),
        ThaiWord(id: 222, thai: "ส้อม", romanization: "sôom", hindiPronunciation: "सॉम", englishMeaning: "fork", hindiMeaning: "काँटा (खाने का)", category: "Food"),

        // MARK: CEFR A1/A2 frequency batch (agent batch 3)
        ThaiWord(id: 223, thai: "เรา", romanization: "rao", hindiPronunciation: "राओ", englishMeaning: "we / us", hindiMeaning: "हम", category: "Grammar Core"),
        ThaiWord(id: 224, thai: "เขา", romanization: "khǎo", hindiPronunciation: "खाओ", englishMeaning: "he / she", hindiMeaning: "वह", category: "Grammar Core"),
        ThaiWord(id: 225, thai: "มัน", romanization: "man", hindiPronunciation: "मन", englishMeaning: "it", hindiMeaning: "यह / वह (वस्तु)", category: "Grammar Core"),
        ThaiWord(id: 226, thai: "ของ", romanization: "khǒong", hindiPronunciation: "खोंग", englishMeaning: "of / belonging to", hindiMeaning: "का / की (संबंध)", category: "Grammar Core"),
        ThaiWord(id: 227, thai: "ใน", romanization: "nai", hindiPronunciation: "नय", englishMeaning: "in / inside", hindiMeaning: "में", category: "Grammar Core"),
        ThaiWord(id: 228, thai: "จาก", romanization: "jàak", hindiPronunciation: "जाक", englishMeaning: "from", hindiMeaning: "से", category: "Grammar Core"),
        ThaiWord(id: 229, thai: "ถึง", romanization: "thǔeng", hindiPronunciation: "थुंग", englishMeaning: "to / until / to arrive", hindiMeaning: "तक / पहुँचना", category: "Grammar Core"),
        ThaiWord(id: 230, thai: "จะ", romanization: "jà", hindiPronunciation: "ज", englishMeaning: "will (future marker)", hindiMeaning: "-गा / -गी (भविष्य)", category: "Grammar Core"),
        ThaiWord(id: 231, thai: "ได้", romanization: "dâi", hindiPronunciation: "दाय", englishMeaning: "can / to get", hindiMeaning: "सकना / पाना", category: "Grammar Core"),
        ThaiWord(id: 232, thai: "เป็น", romanization: "pen", hindiPronunciation: "पेन", englishMeaning: "to be (someone / something)", hindiMeaning: "होना", category: "Grammar Core"),
        ThaiWord(id: 233, thai: "อยู่", romanization: "yùu", hindiPronunciation: "यू", englishMeaning: "to be at / to stay", hindiMeaning: "होना (स्थान पर) / रहना", category: "Grammar Core"),
        ThaiWord(id: 234, thai: "มี", romanization: "mii", hindiPronunciation: "मी", englishMeaning: "to have / there is", hindiMeaning: "होना / पास होना", category: "Grammar Core"),
        ThaiWord(id: 235, thai: "ทุก", romanization: "thúk", hindiPronunciation: "थुक", englishMeaning: "every", hindiMeaning: "हर", category: "Grammar Core"),
        ThaiWord(id: 236, thai: "บาง", romanization: "baang", hindiPronunciation: "बांग", englishMeaning: "some", hindiMeaning: "कुछ", category: "Grammar Core"),
        ThaiWord(id: 237, thai: "ก็", romanization: "kô", hindiPronunciation: "कॉ", englishMeaning: "also / then / so", hindiMeaning: "भी / तो", category: "Grammar Core"),
        ThaiWord(id: 238, thai: "ยัง", romanization: "yang", hindiPronunciation: "यंग", englishMeaning: "still / yet", hindiMeaning: "अभी भी / अभी तक", category: "Grammar Core"),
        ThaiWord(id: 239, thai: "กับ", romanization: "kàp", hindiPronunciation: "कप", englishMeaning: "with", hindiMeaning: "के साथ", category: "Grammar Core"),
        ThaiWord(id: 240, thai: "ที่", romanization: "thîi", hindiPronunciation: "थी", englishMeaning: "at (a place)", hindiMeaning: "पर / में (स्थान)", category: "Grammar Core"),
        ThaiWord(id: 241, thai: "แล้ว", romanization: "láew", hindiPronunciation: "लैव", englishMeaning: "already / then", hindiMeaning: "पहले ही / फिर", category: "Grammar Core"),
        ThaiWord(id: 242, thai: "ต้อง", romanization: "tôong", hindiPronunciation: "तोंग", englishMeaning: "must / have to", hindiMeaning: "पड़ना / ज़रूरी होना", category: "Grammar Core"),
        ThaiWord(id: 243, thai: "อยาก", romanization: "yàak", hindiPronunciation: "याक", englishMeaning: "to want (to do)", hindiMeaning: "चाहना", category: "Grammar Core"),
        ThaiWord(id: 244, thai: "ให้", romanization: "hâi", hindiPronunciation: "हाय", englishMeaning: "to give / for", hindiMeaning: "देना / के लिए", category: "Grammar Core"),
        ThaiWord(id: 245, thai: "ว่า", romanization: "wâa", hindiPronunciation: "वा", englishMeaning: "that (say / think that)", hindiMeaning: "कि", category: "Grammar Core"),
        ThaiWord(id: 246, thai: "ด้วย", romanization: "dûai", hindiPronunciation: "दुआय", englishMeaning: "too / also / as well", hindiMeaning: "भी / साथ में", category: "Grammar Core"),
        ThaiWord(id: 247, thai: "นะ", romanization: "ná", hindiPronunciation: "न", englishMeaning: "softening particle (okay?)", hindiMeaning: "ना (वाक्य नरम करने वाला)", category: "Grammar Core"),
        ThaiWord(id: 248, thai: "เอา", romanization: "ao", hindiPronunciation: "आव", englishMeaning: "to take / want (a thing)", hindiMeaning: "लेना", category: "Verbs"),
        ThaiWord(id: 249, thai: "ดื่ม", romanization: "dùem", hindiPronunciation: "दूम", englishMeaning: "to drink", hindiMeaning: "पीना", category: "Verbs"),
        ThaiWord(id: 250, thai: "ใช้", romanization: "chái", hindiPronunciation: "चाय", englishMeaning: "to use", hindiMeaning: "इस्तेमाल करना", category: "Verbs"),
        ThaiWord(id: 251, thai: "หา", romanization: "hǎa", hindiPronunciation: "हा", englishMeaning: "to look for", hindiMeaning: "ढूँढना", category: "Verbs"),
        ThaiWord(id: 252, thai: "เห็น", romanization: "hěn", hindiPronunciation: "हेन", englishMeaning: "to see", hindiMeaning: "देखना / दिखना", category: "Verbs"),
        ThaiWord(id: 253, thai: "บอก", romanization: "bòok", hindiPronunciation: "बॉक", englishMeaning: "to tell", hindiMeaning: "बताना", category: "Verbs"),
        ThaiWord(id: 254, thai: "ถาม", romanization: "thǎam", hindiPronunciation: "थाम", englishMeaning: "to ask", hindiMeaning: "पूछना", category: "Verbs"),
        ThaiWord(id: 255, thai: "ตอบ", romanization: "tòop", hindiPronunciation: "तॉप", englishMeaning: "to answer", hindiMeaning: "जवाब देना", category: "Verbs"),
        ThaiWord(id: 256, thai: "เล่น", romanization: "lên", hindiPronunciation: "लेन", englishMeaning: "to play", hindiMeaning: "खेलना", category: "Verbs"),
        ThaiWord(id: 257, thai: "เรียน", romanization: "rian", hindiPronunciation: "रियन", englishMeaning: "to study / learn", hindiMeaning: "पढ़ना / सीखना", category: "Verbs"),
        ThaiWord(id: 258, thai: "สอน", romanization: "sǒon", hindiPronunciation: "सॉन", englishMeaning: "to teach", hindiMeaning: "सिखाना / पढ़ाना", category: "Verbs"),
        ThaiWord(id: 259, thai: "จ่าย", romanization: "jàai", hindiPronunciation: "जाय", englishMeaning: "to pay", hindiMeaning: "भुगतान करना / पैसे देना", category: "Verbs"),
        ThaiWord(id: 260, thai: "จำ", romanization: "jam", hindiPronunciation: "जम", englishMeaning: "to remember", hindiMeaning: "याद रखना", category: "Verbs"),
        ThaiWord(id: 261, thai: "ลืม", romanization: "luem", hindiPronunciation: "लूम", englishMeaning: "to forget", hindiMeaning: "भूलना", category: "Verbs"),
        ThaiWord(id: 262, thai: "เริ่ม", romanization: "rêrm", hindiPronunciation: "रर्म", englishMeaning: "to begin / start", hindiMeaning: "शुरू करना", category: "Verbs"),
        ThaiWord(id: 263, thai: "เสร็จ", romanization: "sèt", hindiPronunciation: "सेत", englishMeaning: "to finish / be done", hindiMeaning: "ख़त्म होना / पूरा होना", category: "Verbs"),
        ThaiWord(id: 264, thai: "ส่ง", romanization: "sòng", hindiPronunciation: "सोंग", englishMeaning: "to send", hindiMeaning: "भेजना", category: "Verbs"),
        ThaiWord(id: 265, thai: "รับ", romanization: "ráp", hindiPronunciation: "रप", englishMeaning: "to receive / pick up", hindiMeaning: "लेना / प्राप्त करना", category: "Verbs"),
        ThaiWord(id: 266, thai: "เปลี่ยน", romanization: "plìan", hindiPronunciation: "प्लियन", englishMeaning: "to change", hindiMeaning: "बदलना", category: "Verbs"),
        ThaiWord(id: 267, thai: "เลือก", romanization: "lûeak", hindiPronunciation: "लूअक", englishMeaning: "to choose", hindiMeaning: "चुनना", category: "Verbs"),
        ThaiWord(id: 268, thai: "ใส่", romanization: "sài", hindiPronunciation: "साय", englishMeaning: "to wear / put in", hindiMeaning: "पहनना / डालना", category: "Verbs"),
        ThaiWord(id: 269, thai: "นั่ง", romanization: "nâng", hindiPronunciation: "नंग", englishMeaning: "to sit", hindiMeaning: "बैठना", category: "Verbs"),
        ThaiWord(id: 270, thai: "มาก", romanization: "mâak", hindiPronunciation: "माक", englishMeaning: "very / much / a lot", hindiMeaning: "बहुत / ज़्यादा", category: "Adjectives"),
        ThaiWord(id: 271, thai: "น้อย", romanization: "nói", hindiPronunciation: "नॉय", englishMeaning: "little / few", hindiMeaning: "कम / थोड़ा", category: "Adjectives"),
        ThaiWord(id: 272, thai: "แย่", romanization: "yâe", hindiPronunciation: "यै", englishMeaning: "bad / terrible", hindiMeaning: "बुरा / ख़राब", category: "Adjectives"),
        ThaiWord(id: 273, thai: "ง่วง", romanization: "ngûang", hindiPronunciation: "ङुआङ", englishMeaning: "sleepy / drowsy", hindiMeaning: "नींद आना / उनींदा", category: "Adjectives"),
        ThaiWord(id: 274, thai: "สะอาด", romanization: "sà-àat", hindiPronunciation: "स-आत", englishMeaning: "clean", hindiMeaning: "साफ़", category: "Adjectives"),
        ThaiWord(id: 275, thai: "สกปรก", romanization: "sòk-kà-pròk", hindiPronunciation: "सोक-क-प्रोक", englishMeaning: "dirty", hindiMeaning: "गंदा", category: "Adjectives"),
        ThaiWord(id: 276, thai: "อิ่ม", romanization: "ìm", hindiPronunciation: "इम", englishMeaning: "full (after eating)", hindiMeaning: "पेट भरा हुआ", category: "Adjectives"),
        ThaiWord(id: 277, thai: "ว่าง", romanization: "wâang", hindiPronunciation: "वाङ", englishMeaning: "free / vacant / empty", hindiMeaning: "खाली / फ़ुर्सत में", category: "Adjectives"),
        ThaiWord(id: 278, thai: "อ้วน", romanization: "ûan", hindiPronunciation: "उआन", englishMeaning: "fat / plump", hindiMeaning: "मोटा", category: "Adjectives"),
        ThaiWord(id: 279, thai: "ผอม", romanization: "phǒom", hindiPronunciation: "फॉम", englishMeaning: "thin / skinny (person)", hindiMeaning: "दुबला / पतला", category: "Adjectives"),
        ThaiWord(id: 280, thai: "สั้น", romanization: "sân", hindiPronunciation: "सन", englishMeaning: "short (length)", hindiMeaning: "छोटा (लंबाई में)", category: "Adjectives"),
        ThaiWord(id: 281, thai: "ยาว", romanization: "yaao", hindiPronunciation: "याव", englishMeaning: "long (length)", hindiMeaning: "लंबा", category: "Adjectives"),
        ThaiWord(id: 282, thai: "กว้าง", romanization: "kwâang", hindiPronunciation: "क्वाङ", englishMeaning: "wide / spacious", hindiMeaning: "चौड़ा", category: "Adjectives"),
        ThaiWord(id: 283, thai: "แคบ", romanization: "khâep", hindiPronunciation: "खैप", englishMeaning: "narrow", hindiMeaning: "संकरा / तंग", category: "Adjectives"),
        ThaiWord(id: 284, thai: "หนัก", romanization: "nàk", hindiPronunciation: "नक", englishMeaning: "heavy", hindiMeaning: "भारी", category: "Adjectives"),
        ThaiWord(id: 285, thai: "เบา", romanization: "bao", hindiPronunciation: "बाओ", englishMeaning: "light (weight) / soft (sound)", hindiMeaning: "हल्का / धीमा", category: "Adjectives"),
        ThaiWord(id: 286, thai: "ดัง", romanization: "dang", hindiPronunciation: "दङ", englishMeaning: "loud / famous", hindiMeaning: "तेज़ (आवाज़) / मशहूर", category: "Adjectives"),
        ThaiWord(id: 287, thai: "เงียบ", romanization: "ngîap", hindiPronunciation: "ङियप", englishMeaning: "quiet / silent", hindiMeaning: "शांत / ख़ामोश", category: "Adjectives"),
        ThaiWord(id: 288, thai: "เก่ง", romanization: "kèng", hindiPronunciation: "केङ", englishMeaning: "smart / good at something", hindiMeaning: "होशियार / माहिर", category: "Adjectives"),
        ThaiWord(id: 289, thai: "หอม", romanization: "hǒom", hindiPronunciation: "हॉम", englishMeaning: "fragrant / smells good", hindiMeaning: "खुशबूदार", category: "Adjectives"),
        ThaiWord(id: 290, thai: "สบาย", romanization: "sà-baai", hindiPronunciation: "स-बाय", englishMeaning: "comfortable / relaxed", hindiMeaning: "आरामदायक / आराम से", category: "Adjectives"),
        ThaiWord(id: 291, thai: "สำคัญ", romanization: "sǎm-khan", hindiPronunciation: "सम-खन", englishMeaning: "important", hindiMeaning: "महत्वपूर्ण / ज़रूरी", category: "Adjectives"),
        ThaiWord(id: 292, thai: "ถูกต้อง", romanization: "thùuk-tông", hindiPronunciation: "थूक-तॉङ", englishMeaning: "correct / right", hindiMeaning: "सही", category: "Adjectives"),
        ThaiWord(id: 293, thai: "ผิด", romanization: "phìt", hindiPronunciation: "फित", englishMeaning: "wrong / incorrect", hindiMeaning: "गलत", category: "Adjectives"),
        ThaiWord(id: 294, thai: "สูง", romanization: "sǔung", hindiPronunciation: "सूङ", englishMeaning: "tall / high", hindiMeaning: "ऊँचा / लंबा (कद)", category: "Adjectives"),
        ThaiWord(id: 295, thai: "วันจันทร์", romanization: "wan-jan", hindiPronunciation: "वन-जन", englishMeaning: "Monday", hindiMeaning: "सोमवार", category: "Time"),
        ThaiWord(id: 296, thai: "วันอังคาร", romanization: "wan-ang-khaan", hindiPronunciation: "वन-अंग-खान", englishMeaning: "Tuesday", hindiMeaning: "मंगलवार", category: "Time"),
        ThaiWord(id: 297, thai: "วันพุธ", romanization: "wan-phút", hindiPronunciation: "वन-फुत", englishMeaning: "Wednesday", hindiMeaning: "बुधवार", category: "Time"),
        ThaiWord(id: 298, thai: "วันพฤหัสบดี", romanization: "wan-phá-rúe-hàt-sà-boo-dii", hindiPronunciation: "वन-फ-रु-हत-स-बो-दी", englishMeaning: "Thursday", hindiMeaning: "गुरुवार", category: "Time"),
        ThaiWord(id: 299, thai: "วันศุกร์", romanization: "wan-sùk", hindiPronunciation: "वन-सुक", englishMeaning: "Friday", hindiMeaning: "शुक्रवार", category: "Time"),
        ThaiWord(id: 300, thai: "วันเสาร์", romanization: "wan-sǎo", hindiPronunciation: "वन-साओ", englishMeaning: "Saturday", hindiMeaning: "शनिवार", category: "Time"),
        ThaiWord(id: 301, thai: "วันอาทิตย์", romanization: "wan-aa-thít", hindiPronunciation: "वन-आ-थित", englishMeaning: "Sunday", hindiMeaning: "रविवार", category: "Time"),
        ThaiWord(id: 302, thai: "ตอนนี้", romanization: "toon-níi", hindiPronunciation: "तोन-नी", englishMeaning: "now", hindiMeaning: "अभी", category: "Time"),
        ThaiWord(id: 303, thai: "บ่อย", romanization: "bòi", hindiPronunciation: "बॉय", englishMeaning: "often", hindiMeaning: "अक्सर", category: "Time"),
        ThaiWord(id: 304, thai: "บางครั้ง", romanization: "baang-khráng", hindiPronunciation: "बांग-ख्रंग", englishMeaning: "sometimes", hindiMeaning: "कभी-कभी", category: "Time"),
        ThaiWord(id: 305, thai: "เสมอ", romanization: "sà-měr", hindiPronunciation: "स-मर्", englishMeaning: "always", hindiMeaning: "हमेशा", category: "Time"),
        ThaiWord(id: 306, thai: "ไม่เคย", romanization: "mâi-kheuy", hindiPronunciation: "माय-खर्य", englishMeaning: "never", hindiMeaning: "कभी नहीं", category: "Time"),
        ThaiWord(id: 307, thai: "เร็ว ๆ นี้", romanization: "reo-reo-níi", hindiPronunciation: "रेव-रेव-नी", englishMeaning: "soon", hindiMeaning: "जल्दी ही", category: "Time"),
        ThaiWord(id: 308, thai: "ก่อน", romanization: "kòon", hindiPronunciation: "कोन", englishMeaning: "before / first", hindiMeaning: "पहले / से पहले", category: "Time"),
        ThaiWord(id: 309, thai: "หลัง", romanization: "lǎng", hindiPronunciation: "लंग", englishMeaning: "after", hindiMeaning: "बाद / के बाद", category: "Time"),
        ThaiWord(id: 310, thai: "สาย", romanization: "sǎai", hindiPronunciation: "साय", englishMeaning: "late", hindiMeaning: "देर से (लेट)", category: "Time"),
        ThaiWord(id: 311, thai: "เที่ยง", romanization: "thîang", hindiPronunciation: "थ्यांग", englishMeaning: "noon / midday", hindiMeaning: "दोपहर (12 बजे)", category: "Time"),
        ThaiWord(id: 312, thai: "เสาร์อาทิตย์", romanization: "sǎo-aa-thít", hindiPronunciation: "साओ-आ-थित", englishMeaning: "weekend", hindiMeaning: "वीकेंड / सप्ताहांत", category: "Time"),
        ThaiWord(id: 313, thai: "อาทิตย์หน้า", romanization: "aa-thít-nâa", hindiPronunciation: "आ-थित-ना", englishMeaning: "next week", hindiMeaning: "अगले हफ़्ते", category: "Time"),
        ThaiWord(id: 314, thai: "อาทิตย์ที่แล้ว", romanization: "aa-thít-thîi-láew", hindiPronunciation: "आ-थित-थी-लैव", englishMeaning: "last week", hindiMeaning: "पिछले हफ़्ते", category: "Time"),
        ThaiWord(id: 315, thai: "บ่าย", romanization: "bàai", hindiPronunciation: "बाय", englishMeaning: "afternoon", hindiMeaning: "दोपहर (बाद)", category: "Time"),
        ThaiWord(id: 316, thai: "ทุกวัน", romanization: "thúk-wan", hindiPronunciation: "थुक-वन", englishMeaning: "every day", hindiMeaning: "हर दिन / रोज़", category: "Time"),
        ThaiWord(id: 317, thai: "คืนนี้", romanization: "kheun-níi", hindiPronunciation: "खून-नी", englishMeaning: "tonight", hindiMeaning: "आज रात", category: "Time"),
        ThaiWord(id: 318, thai: "วันหยุด", romanization: "wan-yùt", hindiPronunciation: "वन-युत", englishMeaning: "holiday / day off", hindiMeaning: "छुट्टी", category: "Time"),
        ThaiWord(id: 319, thai: "นาน", romanization: "naan", hindiPronunciation: "नान", englishMeaning: "a long time", hindiMeaning: "देर तक / लंबा समय", category: "Time"),
        ThaiWord(id: 320, thai: "กี่", romanization: "kìi", hindiPronunciation: "की", englishMeaning: "how many", hindiMeaning: "कितने", category: "Numbers"),
        ThaiWord(id: 321, thai: "ตัว", romanization: "tua", hindiPronunciation: "तुआ", englishMeaning: "classifier for animals & clothes", hindiMeaning: "जानवरों/कपड़ों का गिनती-शब्द", category: "Numbers"),
        ThaiWord(id: 322, thai: "คน", romanization: "khon", hindiPronunciation: "खन", englishMeaning: "person / classifier for people", hindiMeaning: "व्यक्ति / लोगों का गिनती-शब्द", category: "Numbers"),
        ThaiWord(id: 323, thai: "อัน", romanization: "an", hindiPronunciation: "अन", englishMeaning: "classifier for small things", hindiMeaning: "छोटी चीज़ों का गिनती-शब्द", category: "Numbers"),
        ThaiWord(id: 324, thai: "ใบ", romanization: "bai", hindiPronunciation: "बै", englishMeaning: "classifier for bags, tickets & leaves", hindiMeaning: "बैग/टिकट/पत्तों का गिनती-शब्द", category: "Numbers"),
        ThaiWord(id: 325, thai: "แก้ว", romanization: "kâew", hindiPronunciation: "कैव", englishMeaning: "glass / glass of (classifier)", hindiMeaning: "गिलास", category: "Numbers"),
        ThaiWord(id: 326, thai: "ขวด", romanization: "khùat", hindiPronunciation: "खुआत", englishMeaning: "bottle / bottle of (classifier)", hindiMeaning: "बोतल", category: "Numbers"),
        ThaiWord(id: 327, thai: "จาน", romanization: "jaan", hindiPronunciation: "चान", englishMeaning: "plate / plate of (classifier)", hindiMeaning: "प्लेट / थाली", category: "Numbers"),
        ThaiWord(id: 328, thai: "ถ้วย", romanization: "thûai", hindiPronunciation: "थुआय", englishMeaning: "cup / bowl (classifier)", hindiMeaning: "कप / कटोरी", category: "Numbers"),
        ThaiWord(id: 329, thai: "คู่", romanization: "khûu", hindiPronunciation: "खू", englishMeaning: "pair / pair of (classifier)", hindiMeaning: "जोड़ा", category: "Numbers"),
        ThaiWord(id: 330, thai: "ชิ้น", romanization: "chín", hindiPronunciation: "छिन", englishMeaning: "piece / piece of (classifier)", hindiMeaning: "टुकड़ा", category: "Numbers"),
        ThaiWord(id: 331, thai: "เล่ม", romanization: "lêm", hindiPronunciation: "लेम", englishMeaning: "classifier for books", hindiMeaning: "किताबों का गिनती-शब्द", category: "Numbers"),
        ThaiWord(id: 332, thai: "ครั้ง", romanization: "khráng", hindiPronunciation: "ख्रंग", englishMeaning: "time / occasion", hindiMeaning: "बार / दफ़ा", category: "Numbers"),
        ThaiWord(id: 333, thai: "ร้อย", romanization: "rói", hindiPronunciation: "रॉय", englishMeaning: "hundred", hindiMeaning: "सौ", category: "Numbers"),
        ThaiWord(id: 334, thai: "พัน", romanization: "phan", hindiPronunciation: "फन", englishMeaning: "thousand", hindiMeaning: "हज़ार", category: "Numbers"),
        ThaiWord(id: 335, thai: "หมื่น", romanization: "mùen", hindiPronunciation: "मून", englishMeaning: "ten thousand", hindiMeaning: "दस हज़ार", category: "Numbers"),
        ThaiWord(id: 336, thai: "แสน", romanization: "sǎen", hindiPronunciation: "सैन", englishMeaning: "hundred thousand", hindiMeaning: "लाख", category: "Numbers"),
        ThaiWord(id: 337, thai: "ล้าน", romanization: "láan", hindiPronunciation: "लान", englishMeaning: "million", hindiMeaning: "दस लाख", category: "Numbers"),
        ThaiWord(id: 338, thai: "ครึ่ง", romanization: "khrûeng", hindiPronunciation: "ख्रुंग", englishMeaning: "half", hindiMeaning: "आधा", category: "Numbers"),
        ThaiWord(id: 339, thai: "นิดหน่อย", romanization: "nít-nòi", hindiPronunciation: "नित-नॉय", englishMeaning: "a little bit", hindiMeaning: "थोड़ा-सा", category: "Numbers"),
        ThaiWord(id: 340, thai: "เยอะ", romanization: "yóe", hindiPronunciation: "यर्", englishMeaning: "a lot / many", hindiMeaning: "बहुत / ढेर सारा", category: "Numbers"),
        ThaiWord(id: 341, thai: "ทั้งหมด", romanization: "tháng-mòt", hindiPronunciation: "थंग-मोत", englishMeaning: "all / total / altogether", hindiMeaning: "सब / कुल", category: "Numbers"),
        ThaiWord(id: 342, thai: "ละ", romanization: "lá", hindiPronunciation: "ल", englishMeaning: "each / per", hindiMeaning: "प्रति / हर एक", category: "Numbers"),
        ThaiWord(id: 343, thai: "ศูนย์", romanization: "sǔun", hindiPronunciation: "सून", englishMeaning: "zero", hindiMeaning: "शून्य", category: "Numbers"),
        ThaiWord(id: 344, thai: "ยี่สิบ", romanization: "yîi-sìp", hindiPronunciation: "यी-सिप", englishMeaning: "twenty", hindiMeaning: "बीस", category: "Numbers"),
        ThaiWord(id: 345, thai: "ห้อง", romanization: "hôong", hindiPronunciation: "हॉंग", englishMeaning: "room", hindiMeaning: "कमरा", category: "Home"),
        ThaiWord(id: 346, thai: "ประตู", romanization: "prà-tuu", hindiPronunciation: "प्र-तू", englishMeaning: "door", hindiMeaning: "दरवाज़ा", category: "Home"),
        ThaiWord(id: 347, thai: "หน้าต่าง", romanization: "nâa-tàang", hindiPronunciation: "ना-तांग", englishMeaning: "window", hindiMeaning: "खिड़की", category: "Home"),
        ThaiWord(id: 348, thai: "เตียง", romanization: "tiang", hindiPronunciation: "तियंग", englishMeaning: "bed", hindiMeaning: "बिस्तर", category: "Home"),
        ThaiWord(id: 349, thai: "โต๊ะ", romanization: "tó", hindiPronunciation: "तो", englishMeaning: "table", hindiMeaning: "मेज़", category: "Home"),
        ThaiWord(id: 350, thai: "เก้าอี้", romanization: "kâo-îi", hindiPronunciation: "काओ-ई", englishMeaning: "chair", hindiMeaning: "कुर्सी", category: "Home"),
        ThaiWord(id: 351, thai: "มือถือ", romanization: "meuu-thěuu", hindiPronunciation: "मू-थू", englishMeaning: "mobile phone", hindiMeaning: "मोबाइल फ़ोन", category: "Home"),
        ThaiWord(id: 352, thai: "กุญแจ", romanization: "kun-jae", hindiPronunciation: "कुन-जै", englishMeaning: "key", hindiMeaning: "चाबी", category: "Home"),
        ThaiWord(id: 353, thai: "เสื้อผ้า", romanization: "sûea-phâa", hindiPronunciation: "सूआ-फा", englishMeaning: "clothes", hindiMeaning: "कपड़े", category: "Home"),
        ThaiWord(id: 354, thai: "กางเกง", romanization: "kaang-keeng", hindiPronunciation: "कांग-केंग", englishMeaning: "pants / trousers", hindiMeaning: "पैंट", category: "Home"),
        ThaiWord(id: 355, thai: "สบู่", romanization: "sà-bùu", hindiPronunciation: "स-बू", englishMeaning: "soap", hindiMeaning: "साबुन", category: "Home"),
        ThaiWord(id: 356, thai: "ผ้าเช็ดตัว", romanization: "phâa-chét-tua", hindiPronunciation: "फा-चेत-तुआ", englishMeaning: "towel", hindiMeaning: "तौलिया", category: "Home"),
        ThaiWord(id: 357, thai: "ไฟฟ้า", romanization: "fai-fáa", hindiPronunciation: "फ़ाइ-फ़ा", englishMeaning: "electricity", hindiMeaning: "बिजली", category: "Home"),
        ThaiWord(id: 358, thai: "แอร์", romanization: "ae", hindiPronunciation: "ऐ", englishMeaning: "air conditioner", hindiMeaning: "एसी", category: "Home"),
        ThaiWord(id: 359, thai: "พัดลม", romanization: "phát-lom", hindiPronunciation: "फत-लोम", englishMeaning: "fan", hindiMeaning: "पंखा", category: "Home"),
        ThaiWord(id: 360, thai: "ตู้เย็น", romanization: "tûu-yen", hindiPronunciation: "तू-येन", englishMeaning: "fridge", hindiMeaning: "फ्रिज", category: "Home"),
        ThaiWord(id: 361, thai: "ทีวี", romanization: "thii-wii", hindiPronunciation: "थी-वी", englishMeaning: "television", hindiMeaning: "टीवी", category: "Home"),
        ThaiWord(id: 362, thai: "โคมไฟ", romanization: "khoom-fai", hindiPronunciation: "खोम-फ़ाइ", englishMeaning: "lamp", hindiMeaning: "लैंप", category: "Home"),
        ThaiWord(id: 363, thai: "ห้องนอน", romanization: "hôong-noon", hindiPronunciation: "हॉंग-नॉन", englishMeaning: "bedroom", hindiMeaning: "बेडरूम", category: "Home"),
        ThaiWord(id: 364, thai: "ห้องครัว", romanization: "hôong-khrua", hindiPronunciation: "हॉंग-ख्रुआ", englishMeaning: "kitchen", hindiMeaning: "रसोई", category: "Home"),
        ThaiWord(id: 365, thai: "แปรงสีฟัน", romanization: "praeng-sǐi-fan", hindiPronunciation: "प्रैंग-सी-फ़न", englishMeaning: "toothbrush", hindiMeaning: "टूथब्रश", category: "Home"),
        ThaiWord(id: 366, thai: "ยาสีฟัน", romanization: "yaa-sǐi-fan", hindiPronunciation: "या-सी-फ़न", englishMeaning: "toothpaste", hindiMeaning: "टूथपेस्ट", category: "Home"),
        ThaiWord(id: 367, thai: "หมอน", romanization: "mǒon", hindiPronunciation: "मॉन", englishMeaning: "pillow", hindiMeaning: "तकिया", category: "Home"),
        ThaiWord(id: 368, thai: "ผ้าห่ม", romanization: "phâa-hòm", hindiPronunciation: "फा-होम", englishMeaning: "blanket", hindiMeaning: "कंबल", category: "Home"),
        ThaiWord(id: 369, thai: "กระจก", romanization: "krà-jòk", hindiPronunciation: "क्र-जोक", englishMeaning: "mirror / glass", hindiMeaning: "शीशा", category: "Home"),
        ThaiWord(id: 370, thai: "ภาษา", romanization: "phaa-sǎa", hindiPronunciation: "फा-सा", englishMeaning: "language", hindiMeaning: "भाषा", category: "Communication"),
        ThaiWord(id: 371, thai: "ภาษาไทย", romanization: "phaa-sǎa-thai", hindiPronunciation: "फा-सा-थाइ", englishMeaning: "Thai language", hindiMeaning: "थाई भाषा", category: "Communication"),
        ThaiWord(id: 372, thai: "ภาษาอังกฤษ", romanization: "phaa-sǎa-ang-krìt", hindiPronunciation: "फा-सा-अंग-क्रित", englishMeaning: "English language", hindiMeaning: "अंग्रेज़ी", category: "Communication"),
        ThaiWord(id: 373, thai: "แปล", romanization: "plae", hindiPronunciation: "प्लै", englishMeaning: "to translate", hindiMeaning: "अनुवाद करना", category: "Communication"),
        ThaiWord(id: 374, thai: "หมายความว่า", romanization: "mǎai-khwaam-wâa", hindiPronunciation: "माय-ख्वाम-वा", englishMeaning: "to mean (that)", hindiMeaning: "मतलब होना", category: "Communication"),
        ThaiWord(id: 375, thai: "โทร", romanization: "thoo", hindiPronunciation: "थो", englishMeaning: "to call (phone)", hindiMeaning: "फ़ोन करना", category: "Communication"),
        ThaiWord(id: 376, thai: "ข้อความ", romanization: "khôo-khwaam", hindiPronunciation: "खॉ-ख्वाम", englishMeaning: "message", hindiMeaning: "संदेश / मैसेज", category: "Communication"),
        ThaiWord(id: 377, thai: "อีเมล", romanization: "ii-meo", hindiPronunciation: "ई-मेव", englishMeaning: "email", hindiMeaning: "ईमेल", category: "Communication"),
        ThaiWord(id: 378, thai: "เบอร์", romanization: "bəə", hindiPronunciation: "बर्", englishMeaning: "(phone) number", hindiMeaning: "फ़ोन नंबर", category: "Communication"),
        ThaiWord(id: 379, thai: "ที่อยู่", romanization: "thîi-yùu", hindiPronunciation: "थी-यू", englishMeaning: "address", hindiMeaning: "पता", category: "Communication"),
        ThaiWord(id: 380, thai: "ชื่อเล่น", romanization: "chêu-lên", hindiPronunciation: "चू-लेन", englishMeaning: "nickname", hindiMeaning: "निकनेम / छोटा नाम", category: "Communication"),
        ThaiWord(id: 381, thai: "นามสกุล", romanization: "naam-sà-kun", hindiPronunciation: "नाम-स-कुन", englishMeaning: "surname / last name", hindiMeaning: "सरनेम / कुलनाम", category: "Communication"),
        ThaiWord(id: 382, thai: "เพื่อนบ้าน", romanization: "phêuan-bâan", hindiPronunciation: "फुअन-बान", englishMeaning: "neighbor", hindiMeaning: "पड़ोसी", category: "Communication"),
        ThaiWord(id: 383, thai: "หัวหน้า", romanization: "hǔa-nâa", hindiPronunciation: "हुअ-ना", englishMeaning: "boss", hindiMeaning: "बॉस", category: "Communication"),
        ThaiWord(id: 384, thai: "เพื่อนร่วมงาน", romanization: "phêuan-rûam-ngaan", hindiPronunciation: "फुअन-रुअम-ङान", englishMeaning: "colleague / coworker", hindiMeaning: "सहकर्मी", category: "Communication"),
        ThaiWord(id: 385, thai: "ประชุม", romanization: "prà-chum", hindiPronunciation: "प्र-चुम", englishMeaning: "meeting", hindiMeaning: "मीटिंग / बैठक", category: "Communication"),
        ThaiWord(id: 386, thai: "งาน", romanization: "ngaan", hindiPronunciation: "ङान", englishMeaning: "work / job", hindiMeaning: "काम / नौकरी", category: "Communication"),
        ThaiWord(id: 387, thai: "คุย", romanization: "khui", hindiPronunciation: "खुय", englishMeaning: "to chat / talk", hindiMeaning: "बात करना", category: "Communication"),
        ThaiWord(id: 388, thai: "คำ", romanization: "kham", hindiPronunciation: "खम", englishMeaning: "word", hindiMeaning: "शब्द", category: "Communication"),
        ThaiWord(id: 389, thai: "ขา", romanization: "khǎa", hindiPronunciation: "खा", englishMeaning: "leg", hindiMeaning: "टांग", category: "Body"),
        ThaiWord(id: 390, thai: "แขน", romanization: "khǎen", hindiPronunciation: "खैन", englishMeaning: "arm", hindiMeaning: "बांह / बाज़ू", category: "Body"),
        ThaiWord(id: 391, thai: "ท้อง", romanization: "thóong", hindiPronunciation: "थॉंग", englishMeaning: "stomach / belly", hindiMeaning: "पेट", category: "Body"),
        ThaiWord(id: 392, thai: "ปาก", romanization: "pàak", hindiPronunciation: "पाक", englishMeaning: "mouth", hindiMeaning: "मुंह", category: "Body"),
        ThaiWord(id: 393, thai: "จมูก", romanization: "jà-mùuk", hindiPronunciation: "जमूक", englishMeaning: "nose", hindiMeaning: "नाक", category: "Body"),
        ThaiWord(id: 394, thai: "หู", romanization: "hǔu", hindiPronunciation: "हू", englishMeaning: "ear", hindiMeaning: "कान", category: "Body"),
        ThaiWord(id: 395, thai: "ผิว", romanization: "phǐw", hindiPronunciation: "फिव", englishMeaning: "skin", hindiMeaning: "त्वचा", category: "Body"),
        ThaiWord(id: 396, thai: "เท้า", romanization: "tháo", hindiPronunciation: "थाव", englishMeaning: "foot", hindiMeaning: "पैर / पांव", category: "Body"),
        ThaiWord(id: 397, thai: "นิ้ว", romanization: "níw", hindiPronunciation: "निव", englishMeaning: "finger", hindiMeaning: "उंगली", category: "Body"),
        ThaiWord(id: 398, thai: "คอ", romanization: "khoo", hindiPronunciation: "खॉ", englishMeaning: "neck / throat", hindiMeaning: "गर्दन / गला", category: "Body"),
        ThaiWord(id: 399, thai: "หน้า", romanization: "nâa", hindiPronunciation: "ना", englishMeaning: "face", hindiMeaning: "चेहरा", category: "Body"),
        ThaiWord(id: 400, thai: "เจ็บ", romanization: "jèp", hindiPronunciation: "जेप", englishMeaning: "to hurt / painful", hindiMeaning: "दर्द होना / चोट लगना", category: "Body"),
        ThaiWord(id: 401, thai: "ไข้", romanization: "khâi", hindiPronunciation: "खइ", englishMeaning: "fever", hindiMeaning: "बुखार", category: "Body"),
        ThaiWord(id: 402, thai: "ไอ", romanization: "ai", hindiPronunciation: "अइ", englishMeaning: "to cough", hindiMeaning: "खांसना / खांसी", category: "Body"),
        ThaiWord(id: 403, thai: "หวัด", romanization: "wàt", hindiPronunciation: "वत", englishMeaning: "cold (illness)", hindiMeaning: "ज़ुकाम / सर्दी", category: "Body"),
        ThaiWord(id: 404, thai: "ยาแก้ปวด", romanization: "yaa-kâe-pùat", hindiPronunciation: "या-कै-पुआत", englishMeaning: "painkiller", hindiMeaning: "दर्द की दवा / पेनकिलर", category: "Body"),
        ThaiWord(id: 405, thai: "แพ้", romanization: "pháe", hindiPronunciation: "फै", englishMeaning: "allergic to", hindiMeaning: "एलर्जी होना", category: "Body"),
        ThaiWord(id: 406, thai: "เลือด", romanization: "lûeat", hindiPronunciation: "लूअत", englishMeaning: "blood", hindiMeaning: "खून", category: "Body"),
        ThaiWord(id: 407, thai: "แผล", romanization: "phlǎe", hindiPronunciation: "फ्लै", englishMeaning: "wound / cut", hindiMeaning: "घाव / ज़ख्म", category: "Body"),
        ThaiWord(id: 408, thai: "อุบัติเหตุ", romanization: "ù-bàt-tì-hèet", hindiPronunciation: "उ-बत-ति-हेत", englishMeaning: "accident", hindiMeaning: "दुर्घटना / एक्सीडेंट", category: "Body"),
        ThaiWord(id: 409, thai: "รถพยาบาล", romanization: "rót-phá-yaa-baan", hindiPronunciation: "रोत-फ-या-बान", englishMeaning: "ambulance", hindiMeaning: "एम्बुलेंस", category: "Body"),
        ThaiWord(id: 410, thai: "ร้านขายยา", romanization: "ráan-khǎai-yaa", hindiPronunciation: "रान-खाय-या", englishMeaning: "pharmacy", hindiMeaning: "दवाई की दुकान / फार्मेसी", category: "Body"),
        ThaiWord(id: 411, thai: "ประกัน", romanization: "prà-kan", hindiPronunciation: "प्र-कन", englishMeaning: "insurance", hindiMeaning: "बीमा", category: "Body"),
        ThaiWord(id: 412, thai: "พักผ่อน", romanization: "phák-phòn", hindiPronunciation: "फक-फॉन", englishMeaning: "to rest / relax", hindiMeaning: "आराम करना", category: "Body"),

        // MARK: Months of the year
        ThaiWord(id: 413, thai: "มกราคม", romanization: "mók-kà-raa-khom", hindiPronunciation: "मोक-क-रा-खोम", englishMeaning: "January", hindiMeaning: "जनवरी", category: "Months"),
        ThaiWord(id: 414, thai: "กุมภาพันธ์", romanization: "kum-phaa-phan", hindiPronunciation: "कुम-पा-पन", englishMeaning: "February", hindiMeaning: "फ़रवरी", category: "Months"),
        ThaiWord(id: 415, thai: "มีนาคม", romanization: "mii-naa-khom", hindiPronunciation: "मी-ना-खोम", englishMeaning: "March", hindiMeaning: "मार्च", category: "Months"),
        ThaiWord(id: 416, thai: "เมษายน", romanization: "mee-sǎa-yon", hindiPronunciation: "मे-सा-योन", englishMeaning: "April", hindiMeaning: "अप्रैल", category: "Months"),
        ThaiWord(id: 417, thai: "พฤษภาคม", romanization: "phrúet-sà-phaa-khom", hindiPronunciation: "प्रुत-स-पा-खोम", englishMeaning: "May", hindiMeaning: "मई", category: "Months"),
        ThaiWord(id: 418, thai: "มิถุนายน", romanization: "mí-thù-naa-yon", hindiPronunciation: "मि-थु-ना-योन", englishMeaning: "June", hindiMeaning: "जून", category: "Months"),
        ThaiWord(id: 419, thai: "กรกฎาคม", romanization: "kà-rá-kà-daa-khom", hindiPronunciation: "क-र-क-दा-खोम", englishMeaning: "July", hindiMeaning: "जुलाई", category: "Months"),
        ThaiWord(id: 420, thai: "สิงหาคม", romanization: "sǐng-hǎa-khom", hindiPronunciation: "सिंग-हा-खोम", englishMeaning: "August", hindiMeaning: "अगस्त", category: "Months"),
        ThaiWord(id: 421, thai: "กันยายน", romanization: "kan-yaa-yon", hindiPronunciation: "कन-या-योन", englishMeaning: "September", hindiMeaning: "सितंबर", category: "Months"),
        ThaiWord(id: 422, thai: "ตุลาคม", romanization: "tù-laa-khom", hindiPronunciation: "तु-ला-खोम", englishMeaning: "October", hindiMeaning: "अक्टूबर", category: "Months"),
        ThaiWord(id: 423, thai: "พฤศจิกายน", romanization: "phrúet-sà-jì-kaa-yon", hindiPronunciation: "प्रुत-स-जि-का-योन", englishMeaning: "November", hindiMeaning: "नवंबर", category: "Months"),
        ThaiWord(id: 424, thai: "ธันวาคม", romanization: "than-waa-khom", hindiPronunciation: "तन-वा-खोम", englishMeaning: "December", hindiMeaning: "दिसंबर", category: "Months"),
        ThaiWord(id: 425, thai: "นี้", romanization: "níi", hindiPronunciation: "नी", englishMeaning: "this (after a noun)", hindiMeaning: "यह (संज्ञा के बाद)", category: "Grammar Core"),
        ThaiWord(id: 426, thai: "ขอ", romanization: "khǒo", hindiPronunciation: "खो", englishMeaning: "may I have / to ask for", hindiMeaning: "माँगना / दीजिए", category: "Verbs"),
        ThaiWord(id: 427, thai: "ไหม", romanization: "mǎi", hindiPronunciation: "माइ", englishMeaning: "question particle (yes/no)", hindiMeaning: "प्रश्न-सूचक शब्द (हाँ/नहीं)", category: "Grammar Core"),
        ThaiWord(id: 428, thai: "หน่อย", romanization: "nòi", hindiPronunciation: "नोइ", englishMeaning: "a little / please (softener)", hindiMeaning: "ज़रा / थोड़ा (नरम अनुरोध)", category: "Grammar Core"),
        ThaiWord(id: 429, thai: "ไทย", romanization: "thai", hindiPronunciation: "थाइ", englishMeaning: "Thai / Thailand", hindiMeaning: "थाई / थाईलैंड", category: "Places"),
        ThaiWord(id: 430, thai: "ตก", romanization: "tòk", hindiPronunciation: "तोक", englishMeaning: "to fall (rain falls)", hindiMeaning: "गिरना (बारिश होना)", category: "Verbs"),
        ThaiWord(id: 431, thai: "กัน", romanization: "kan", hindiPronunciation: "गन", englishMeaning: "together / each other", hindiMeaning: "साथ में / आपस में", category: "Grammar Core"),
        ThaiWord(id: 432, thai: "คือ", romanization: "khuue", hindiPronunciation: "खू", englishMeaning: "is / namely (A is B)", hindiMeaning: "है / यानी", category: "Grammar Core"),
        ThaiWord(id: 433, thai: "อย่า", romanization: "yàa", hindiPronunciation: "या", englishMeaning: "don't (prohibition)", hindiMeaning: "मत (मनाही)", category: "Grammar Core"),
        ThaiWord(id: 434, thai: "ตอน", romanization: "toon", hindiPronunciation: "तोन", englishMeaning: "period of time / when", hindiMeaning: "समय / के समय", category: "Time"),
        ThaiWord(id: 435, thai: "บน", romanization: "bon", hindiPronunciation: "बोन", englishMeaning: "on / on top of", hindiMeaning: "पर / के ऊपर", category: "Directions"),
        ThaiWord(id: 436, thai: "ไหน", romanization: "nǎi", hindiPronunciation: "नाइ", englishMeaning: "which / where", hindiMeaning: "कौन-सा / कहाँ", category: "Questions"),
        ThaiWord(id: 437, thai: "ล้าง", romanization: "láang", hindiPronunciation: "लांग", englishMeaning: "to wash", hindiMeaning: "धोना", category: "Verbs"),
        ThaiWord(id: 438, thai: "เลี้ยว", romanization: "líao", hindiPronunciation: "लियाव", englishMeaning: "to turn", hindiMeaning: "मुड़ना", category: "Directions"),
        ThaiWord(id: 439, thai: "เลย", romanization: "loei", hindiPronunciation: "लर्य", englishMeaning: "at all / completely (emphasis)", hindiMeaning: "बिल्कुल / एकदम (ज़ोर)", category: "Grammar Core"),
        ThaiWord(id: 440, thai: "หนังสือ", romanization: "nǎng-sǔue", hindiPronunciation: "नंग-सू", englishMeaning: "book", hindiMeaning: "किताब", category: "Communication"),
        ThaiWord(id: 441, thai: "อายุ", romanization: "aa-yú", hindiPronunciation: "आ-यु", englishMeaning: "age", hindiMeaning: "उम्र / आयु", category: "People"),
        ThaiWord(id: 442, thai: "ยก", romanization: "yók", hindiPronunciation: "योक", englishMeaning: "to lift / raise", hindiMeaning: "उठाना", category: "Verbs"),
        ThaiWord(id: 443, thai: "ค่า", romanization: "khâa", hindiPronunciation: "खा", englishMeaning: "fee / cost", hindiMeaning: "शुल्क / क़ीमत", category: "Money"),
        ThaiWord(id: 444, thai: "อีก", romanization: "ìik", hindiPronunciation: "ईक", englishMeaning: "again / more", hindiMeaning: "फिर से / और", category: "Grammar Core"),
        ThaiWord(id: 445, thai: "แห้ง", romanization: "hâeng", hindiPronunciation: "हैंग", englishMeaning: "dry", hindiMeaning: "सूखा", category: "Adjectives"),
        ThaiWord(id: 446, thai: "เลิก", romanization: "lôek", hindiPronunciation: "लर्क", englishMeaning: "to quit / finish work", hindiMeaning: "छोड़ना / काम ख़त्म होना", category: "Verbs"),
        ThaiWord(id: 447, thai: "คัน", romanization: "khan", hindiPronunciation: "खन", englishMeaning: "classifier for vehicles", hindiMeaning: "गाड़ियों का गिनती-शब्द", category: "Numbers"),
        ThaiWord(id: 448, thai: "อินเดีย", romanization: "in-dia", hindiPronunciation: "इन-दिया", englishMeaning: "India", hindiMeaning: "भारत", category: "Places"),
        ThaiWord(id: 449, thai: "เชียงใหม่", romanization: "chiang-mài", hindiPronunciation: "चियांग-माइ", englishMeaning: "Chiang Mai (city)", hindiMeaning: "चियांग माई (शहर)", category: "Places"),
        ThaiWord(id: 450, thai: "กรุงเทพ", romanization: "krung-thêep", hindiPronunciation: "ग्रुंग-थेब", englishMeaning: "Bangkok", hindiMeaning: "बैंकॉक", category: "Places"),
    ]

    /// Words whose Thai spelling contains this word, or that this word
    /// contains — e.g. น้ำ → ห้องน้ำ, น้ำตาล, น้ำแข็ง. Powers the
    /// "related words" chips in Practice.
    static func related(to word: ThaiWord) -> [ThaiWord] {
        all.filter { $0.id != word.id && ($0.thai.contains(word.thai) || word.thai.contains($0.thai)) }
    }

    /// A stable, per-day rotation offset so the "word of the day" changes daily.
    static func word(forDayOffset offset: Int) -> ThaiWord {
        let index = ((offset % all.count) + all.count) % all.count
        return all[index]
    }

    /// A random word (used by the widget's rotation and the app's shuffle button).
    static func randomWord() -> ThaiWord {
        all.randomElement() ?? all[0]
    }

    /// A stable per-hour word shared by every widget, so widgets placed
    /// side by side always show the same word. The prime stride (17 is
    /// coprime with the list size) pseudo-shuffles the rotation so
    /// consecutive hours don't show consecutive list entries.
    static func word(forHour hour: Int) -> ThaiWord {
        let index = ((hour * 17) % all.count + all.count) % all.count
        return all[index]
    }

    static var categories: [String] {
        var seen = Set<String>()
        return all.compactMap { seen.insert($0.category).inserted ? $0.category : nil }
    }
}
